@url = http://localhost:3000/node-business/
@contentType = content-type: application/json
@module=store

### get 查询
get {{url}}{{module}}/get


### add 添加
post {{url}}{{module}}/add
{{contentType}}

{
    "name": "佛山顺联国际",
    "provincial": "广东省",
    "urban": "佛山市",
    "areas": "禅城区",
    "location": "季华五路33号顺联国际购物中心4F傲胜专柜"
}

### detail 详情
post {{url}}{{module}}/detail/63
{{contentType}}


### mod 修改
post {{url}}{{module}}/mod
{{contentType}}

{
"_id": "5f030b4bdc8e0c03bc48fb57",
"id": "58",
"name": "先天下购物广场",
"provincial": "河北省",
"urban": "石家庄市",
"areas": "长安区",
"location": "中山东路326号",
"status": "1",
"__v": 0
}


### del 删除
post {{url}}{{module}}/detail/
{{contentType}}





