@url = http://localhost:3000/node-business/
@contentType = content-type: application/json
@module=site

### get 查询
get {{url}}{{module}}/get


### add 添加
post {{url}}{{module}}/add
{{contentType}}

{
    "id": 44,
    "name": "沈阳万象城",
    "provincial": "辽宁省",
    "urban": "沈阳市",
    "areas": "和平区",
    "location": "青年大街288号华润万象城",
    "devicecnt": 1,
    "status": "1"
}

### detail 详情
post {{url}}{{module}}/detail/
{{contentType}}


### mod 修改
post {{url}}{{module}}/mod/
{{contentType}}

{}


### del 删除
post {{url}}{{module}}/detail/
{{contentType}}





