@url = http://localhost:3000/node-business/
@contentType = content-type: application/json
@module=systemLog

### get 查询
post {{url}}{{module}}/get


### add 添加
post {{url}}{{module}}/add
{{contentType}}

[
    {
        "ip": "172.19.0.1:61422",
        "account": "18013959588",
        "createtime": "2020-09-22T17:41:15.355502",
        "action": "查询统计",
        "object": "站点",
        "remark": "成功"
    },
    {
        "ip": "172.19.0.1:61420",
        "account": "18013959588",
        "createtime": "2020-09-22T17:41:15.350678",
        "action": "查询统计",
        "object": "设备数量",
        "remark": "成功"
    },
    {
        "ip": "172.19.0.1:61350",
        "account": "18013959588",
        "createtime": "2020-09-22T17:40:54.725937",
        "action": "查询统计",
        "object": "站点",
        "remark": "成功"
    },
    {
        "ip": "172.19.0.1:61342",
        "account": "18013959588",
        "createtime": "2020-09-22T17:40:54.723476",
        "action": "查询统计",
        "object": "设备数量",
        "remark": "成功"
    },
    {
        "ip": "172.19.0.1:61324",
        "account": "18013959588",
        "createtime": "2020-09-22T17:40:35.132069",
        "action": "添加",
        "object": "站点",
        "remark": "成功"
    },
    {
        "ip": "172.19.0.1:61328",
        "account": "18013959588",
        "createtime": "2020-09-22T17:40:35.129829",
        "action": "查询省",
        "object": "站点",
        "remark": "成功"
    },
    {
        "ip": "172.19.0.1:61288",
        "account": "18013959588",
        "createtime": "2020-09-22T17:40:17.134404",
        "action": "添加",
        "object": "站点",
        "remark": "成功"
    },
    {
        "ip": "172.19.0.1:61290",
        "account": "18013959588",
        "createtime": "2020-09-22T17:40:17.130446",
        "action": "查询省",
        "object": "站点",
        "remark": "成功"
    },
    {
        "ip": "172.19.0.1:61252",
        "account": "18013959588",
        "createtime": "2020-09-22T17:40:14.538507",
        "action": "查询统计",
        "object": "设备数量",
        "remark": "成功"
    },
    {
        "ip": "172.19.0.1:61260",
        "account": "18013959588",
        "createtime": "2020-09-22T17:40:14.53717",
        "action": "查询统计",
        "object": "站点",
        "remark": "成功"
    },
    {
        "ip": "172.19.0.1:61188",
        "account": "18013959588",
        "createtime": "2020-09-22T17:40:02.871334",
        "action": "查询统计",
        "object": "站点",
        "remark": "成功"
    },
    {
        "ip": "172.19.0.1:61184",
        "account": "18013959588",
        "createtime": "2020-09-22T17:40:02.869386",
        "action": "查询统计",
        "object": "设备数量",
        "remark": "成功"
    },
    {
        "ip": "172.19.0.1:60968",
        "account": "18013959588",
        "createtime": "2020-09-22T17:31:20.144502",
        "action": "查询统计",
        "object": "设备数量",
        "remark": "成功"
    },
    {
        "ip": "172.19.0.1:60972",
        "account": "18013959588",
        "createtime": "2020-09-22T17:31:20.142036",
        "action": "查询统计",
        "object": "站点",
        "remark": "成功"
    },
    {
        "ip": "172.19.0.1:60924",
        "account": "18013959588",
        "createtime": "2020-09-22T17:30:47.619949",
        "action": "查询统计",
        "object": "站点",
        "remark": "成功"
    }
]

### detail 详情
post {{url}}{{module}}/detail/
{{contentType}}


### mod 修改
post {{url}}{{module}}/mod/
{{contentType}}

{}


### del 删除
post {{url}}{{module}}/detail/
{{contentType}}





