@url='http://localhost:3000'
@contentType=content-type: application/json

### get
get http://localhost:3000/node-business

### login
post http://localhost:3000/node-business/user/login
{{contentType}}

{
  "username":"Juliette",
  "password":"123456"
}
